// Built-in PPM analyser.
//
// Measures whatever arrives on SELFTEST_PIN and reports idle level, mark width,
// frame length and the decoded channel values. Jumper an output to this pin and
// the board checks its own signal -- no oscilloscope and no second Pico.
//
// Runs entirely on GPIO interrupts. The PPM outputs are generated by PIO and
// DMA, so this cannot disturb their timing.

#ifndef LIGHTSHOW_SELFTEST_H
#define LIGHTSHOW_SELFTEST_H

#include <stdbool.h>
#include <stddef.h>

// Free pin, deliberately away from the eight outputs on GPIO2..9.
#define SELFTEST_PIN 10

void selftest_init(void);

// Writes one human readable report into `buf`. Returns false when nothing has
// been seen since the last call, so the caller can stay quiet.
bool selftest_report(char *buf, size_t len);

#endif // LIGHTSHOW_SELFTEST_H
