// Configuration for the airborne light controller.
//
// Normally you do not edit this file. The web UI generates a header per model
// from show.yaml and the build picks it up:
//
//   cmake -S firmware/plane -B build/plane-eule -DPLANE_CONFIG=generated/eule.h
//
// What follows below is the fallback used when no model header is given -- a
// working two-strip, two-relay example that also documents every field.

#ifndef PLANE_CONFIG_H
#define PLANE_CONFIG_H

#include "outputs.h"

#ifdef PLANE_CONFIG_HEADER
#include PLANE_CONFIG_HEADER
#else

// Name reported at boot. A generated header carries the real model name.
#define PLANE_MODEL_NAME "beispiel"


// ---------------------------------------------------------------- general ---

#define RENDER_HZ 200   // effect update rate, independent of the RC rate

// Global ceiling on brightness, 0..255. Keeps the current draw and the pilot's
// night vision in check; the show dimmer scales below this.
#define MAX_BRIGHTNESS 200

// ------------------------------------------------------------- RC input -----
//
// Each model has its own receiver on its own transmitter, so this is about one
// aircraft's channels. The receiver talks SBUS and nothing else: one wire
// instead of four, and all 16 channels are there -- room for several zones at
// four channels each. Without fresh frames the model runs its failsafe.

#define SBUS_UART      uart1
#define SBUS_RX_PIN    5

// Channel range, matching min_us/max_us in show.yaml.
#define RC_MIN_US 1000
#define RC_MAX_US 2000

// Number of cue steps; must match `quantize` on the cue channel.
#define CUE_STEPS 32

// No valid RC data for this long -> failsafe pattern, relays off.
#define RC_TIMEOUT_MS 500

// ------------------------------------------------------------------ zones ---
//
// Each zone owns four consecutive RC channels: cue, hue, brightness, param.
// base_channel is counted as the transmitter counts, starting at 1. A model at
// tx_offset 4 in show.yaml uses base_channel 5.
//
// One zone is the normal case. Add a second one only if a part of the model
// should run a different effect -- it costs another four channels.

#define ZONE_COUNT 1
#define ZONES { \
    /* base_channel */ \
    {1},               \
}

// ----------------------------------------------------------------- strips ---
//
// pin, count, zone, offset, reverse
//
// `offset` places the strip inside its zone's virtual chain:
//   - same offset on two strips  -> they mirror each other
//   - consecutive offsets        -> one long chain a chase runs across
// `reverse` flips a strip that is mounted the other way round, so a chase
// running outwards really runs outwards on both wings.
//
// Every strip needs its own PIO state machine; eight are available.
// Data lines go through a 74AHCT125 level shifter, see hardware/README.md.

#define STRIP_COUNT 2
#define STRIPS { \
    /* left wing, runs outward  */ {2, 30, 0,  0, false}, \
    /* right wing, mirrored     */ {3, 30, 0,  0, true},  \
}

// ----------------------------------------------------------------- relays ---
//
// pin, zone, source, arg, threshold, active_low, min_on_ms, min_off_ms
//
// Sources:
//   RELAY_SRC_PIXEL       follows pixel `arg` of the zone -- blinks exactly
//                         with the effect, costs no RC channel
//   RELAY_SRC_BRIGHTNESS  on while the master dimmer exceeds `threshold`
//   RELAY_SRC_CUE         on from cue `arg` upwards
//   RELAY_SRC_CHANNEL     on while RC channel `arg` exceeds `threshold`
//
// min_on_ms / min_off_ms:
//   0 / 0    MOSFET or solid state -- follows any pattern
//   50 / 50  mechanical relay -- rides on a strobe without chattering itself
//            to death, it simply switches less often than the LEDs
//
// active_low: true for the usual opto-isolated relay boards, false for a
// MOSFET driven straight from the pin.
//
// Cue 0 switches every relay off, regardless of its source.

#define RELAY_COUNT 2
#define RELAYS { \
    /* landing light, MOSFET, blinks with the effect */ \
    {6, 0, RELAY_SRC_PIXEL, 0, 64, false, 0, 0},        \
    /* smoke system, mechanical board, from cue 5 up   */ \
    {7, 0, RELAY_SRC_CUE,   5,  0, true, 200, 200},     \
}

// ------------------------------------------------------- navigation lights --
//
// strip, index, r, g, b
//
// Drawn on top of every effect, so they are always on and always the same
// colour. The pilot needs them to see the aircraft's attitude -- do not fold
// them into the show. Set NAV_COUNT to 0 if this model carries separate,
// permanently wired navigation lights.

#define NAV_COUNT 3
#define NAV_LIGHTS { \
    {0,  0, 255,   0,   0},  /* left wingtip, red    */ \
    {1,  0,   0, 255,   0},  /* right wingtip, green */ \
    {0, 29, 255, 255, 255},  /* tail, white          */ \
}

#endif // PLANE_CONFIG_HEADER

#endif // PLANE_CONFIG_H
